spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Config
file.upload-dir=uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

cloudinary.cloud-name=dhrm8xrbu
cloudinary.api-key=619827588119471
cloudinary.api-secret=d4wjFHR-bdhRsQ4GdVYFWGjbP1s

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=av2000546@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=av2000546@gmail.com
